import type { Metadata } from "next";
import { ADLaM_Display } from "next/font/google";
import "./globals.css";


const geistSans = ADLaM_Display({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: '400'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={geistSans.className}>
        {children}
      </body>
    </html>
  );
}
